import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body className={inter.className}>
				<div className="container mx-auto max-w-[1112px]">
					<Header />
				</div>
				<main className="container mx-auto max-w-[1112px] py-[30px] px-[20px]">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
